# Generated by Django 3.2.9 on 2022-05-10 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set here the name of the project', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Set here the address of the project', max_length=200, null=True)),
                ('latitude_min', models.DecimalField(blank=True, decimal_places=7, help_text='Set here latitude min', max_digits=12, null=True)),
                ('latitude_max', models.DecimalField(blank=True, decimal_places=7, help_text='Set here latitude max', max_digits=12, null=True)),
                ('longitude_min', models.DecimalField(blank=True, decimal_places=7, help_text='Set here longitude min', max_digits=12, null=True)),
                ('longitude_max', models.DecimalField(blank=True, decimal_places=7, help_text='Set here longitude max', max_digits=12, null=True)),
                ('factured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique ID by user/worker', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='worker name', max_length=200)),
                ('surname', models.CharField(help_text='worker surname', max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=10)),
                ('job', models.CharField(blank=True, choices=[('tap', 'Tapper'), ('pai', 'Painter'), ('stl', 'Steel-framer'), ('adm', 'Administrator')], default='bui', help_text='Job of worker', max_length=3)),
            ],
            options={
                'ordering': ['job'],
            },
        ),
    ]
