# Generated by Django 3.2.9 on 2022-05-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0002_auto_20220511_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude_max',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Set here latitude max', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude_min',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Set here latitude min', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude_max',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Set here longitude max', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude_min',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Set here longitude min', max_digits=25, null=True),
        ),
    ]
