# Generated by Django 3.2.9 on 2022-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0003_auto_20220511_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lat_long',
            field=models.CharField(blank=True, help_text='Set here latitude and longitude of the project', max_length=200, null=True),
        ),
    ]
