# Generated by Django 3.2.9 on 2022-05-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0005_project_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.CharField(blank=True, choices=[('Tapper', 'Tapper'), ('Painter', 'Painter'), ('Steel-framer', 'Steel-framer'), ('Administrator', 'Administrator')], default='bui', help_text='Job of worker', max_length=20),
        ),
    ]
