# Generated by Django 3.2.9 on 2022-05-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('can_mark_factured', 'can_mark_factured'), ('can_edit', 'can_edit'))},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['surname']},
        ),
    ]
