# Generated by Django 3.2.9 on 2022-05-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0010_auto_20220515_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latitude_min',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude_min',
        ),
    ]
