# Generated by Django 3.2.9 on 2022-05-22 20:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('timingcontrol', '0011_auto_20220522_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('job', models.CharField(blank=True, choices=[('Tapper', 'Tapper'), ('Painter', 'Painter'), ('Steel-framer', 'Steel-framer'), ('Administrator', 'Administrator')], default='bui', help_text='Job of worker', max_length=20)),
                ('dni', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
