# Generated by Django 3.2.9 on 2022-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timingcontrol', '0015_auto_20220612_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='worked_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
